#ifndef _BBPG_USER_SETUP_H_
#define _BBPG_USER_SETUP_H_

#define UART1_BAUDRATE     	UART_BAUDRATE_115K2       // Baudrate in bits/s: {9K6, 14K4, 19K2, 28K8, 38K4, 57K6, 115K2}
#define UART1_DATALENGTH   	UART_CHARFORMAT_8         // Datalength in bits: {5, 6, 7, 8}
#define UART1_PARITY       	UART_PARITY_NONE          // Parity: {UART_PARITY_NONE, UART_PARITY_EVEN, UART_PARITY_ODD}
#define UART1_STOPBITS     	UART_STOPBITS_1           // Stop bits: {UART_STOPBITS_1, UART_STOPBITS_2} 
#define UART1_FLOWCONTROL  	UART_FLOWCONTROL_DISABLED // Flow control: {UART_FLOWCONTROL_DISABLED, UART_FLOWCONTROL_ENABLED}

#define UART1_GPIO_PORT    	GPIO_PORT_0
#define UART1_TX_PIN       	GPIO_PIN_2
#define UART1_RX_PIN       	GPIO_PIN_3

#define UART_PRINTF_BUFFER_SIZE 128

#define MPU_I2C_GPIO_PORT  	GPIO_PORT_0
#define MPU_I2C_SCL_PIN    	GPIO_PIN_4
#define MPU_I2C_SDA_PIN    	GPIO_PIN_5

#define LED_PORT			GPIO_PORT_2
#define LED_RED_PIN		    GPIO_PIN_5
#define LED_GREEN_PIN		GPIO_PIN_6

#define SOUNDER_PORT        GPIO_PORT_2
#define SOUNDER_PIN         GPIO_PIN_7

#define MOTOR_PORT          GPIO_PORT_2
#define MOTOR_PIN           GPIO_PIN_8

#define OLED_POWER_GPIO_PORT GPIO_PORT_1
#define OLED_POWER_GPIO_PIN  GPIO_PIN_2

#define OLED_I2C_GPIO_PORT 	GPIO_PORT_0
#define OLED_I2C_SCL_PIN	GPIO_PIN_6
#define OLED_I2C_SDA_PIN	GPIO_PIN_7

#define OLED_RES_PORT       GPIO_PORT_1
#define OLED_RES_PIN        GPIO_PIN_1

#define TOUCH_IO_PORT       GPIO_PORT_2
#define TOUCH_IO_PIN        GPIO_PIN_2

//INTC
#define UNDO_DETECT_PORT    GPIO_PORT_2   
#define UNDO_DETECT_PIN     GPIO_PIN_9

//INTA
#define CUT_DETECT_PORT     GPIO_PORT_2
#define CUT_DETECT_PIN      GPIO_PIN_3

#define SYSTEM_TIME_PERIOD  100 // unit ms

#define BBPG_IDENTIFY_TIME  1000 // 10s

typedef enum
{
    BBPG_UI_LAUNCH = 0,
    BBPG_UI_WAIT_CONNECT_1,
    BBPG_UI_WAIT_CONNECT_2,
    BBPG_UI_IDENTIFY_1,
    BBPG_UI_IDENTIFY_2,
    BBPG_UI_CONNECT_OK_1,
    BBPG_UI_CONNECT_OK_2,
    //BBPG_UI_ON_CONNECTION,
    
    BBPG_UI_IDENTIFY_SUCCESS,
    BBPG_UI_IDENTIFY_FAIL,
    
    BBPG_UI_CONNECT_LOSS_1,
    BBPG_UI_CONNECT_LOSS_2,
    
    BBPG_UI_SLEEP,
    BBPG_UI_WAKE_UP,
    
}BBPG_UI_STATE_T;

typedef enum
{
    BBPG_NO_CONNECTION = 0,
    BBPG_IDENTIFY,
    BBPG_HAVE_CONNECTION,
    
    BBPG_HAVE_CONNECTION_OLED_SLEEP,
    
    BBPG_HAVE_CONNECTION_UNDO_CHECK,
    BBPG_HAVE_CONNECTION_CUT_CHECK,
}BBPG_STATE_T;

typedef enum
{
    BBPG_UNDO_DETECT_NO_WORK,
    BBPG_UNDO_DETECT_SAFE,
    BBPG_UNDO_DETECT_ALARM,
}BBPG_UNDO_DETECT_STATE_T;

extern BBPG_STATE_T BBPG_STATE;
extern BBPG_UI_STATE_T BBPG_UI_STATE;
extern BBPG_UNDO_DETECT_STATE_T BBPG_UNDO_STATE;

#endif



