#ifndef _BBPG_EVENT_SCHEDULE_H_
#define _BBPG_EVENT_SCHEDULE_H_

typedef enum
{
    BBPG_EVENT_INPUT_BLE_CONNECT_COMPLETE,
    BBPG_EVENT_INPUT_BLE_DISCONNECT,
    BBPG_EVENT_INPUT_INIT_OVER_START_ADV,
    
    BBPG_EVENT_INPUT_UNDO_ALARM,
    BBPG_EVENT_INPUT_UNDO_SAFE,
    
    BBPG_EVENT_INPUT_TOUCH_DETECT,
    
    BBPG_EVENT_INPUT_IDENTIFY_SUCCESS,
    
    BBPG_EVENT_INPUT_ORDER_DISPLAY_TIMEOUT,
}BBPG_EVENT_INPUT_TYPE_T;

//typedef enum
//{
//    BBPG_IDENTIFY_OK,
//    BBPG_IDENTIFY_NO,
//}BBPG_IDENTIFY_STATE_T;

typedef enum
{
    BBPG_SLEEP,
    BBPG_WAKE_UP,
}BBPG_OLED_SLEEP_STATE_T;

typedef enum
{
    BBPG_LAUNCH,
    BBPG_CONNECTED,
    BBPG_WAIT_CONNECT,
    BBPG_DISCONNECTED,
}BBPG_CONNECTION_STATE_T;

enum
{
    DISABLE,
    ENABLE,
};

extern BBPG_CONNECTION_STATE_T  BBPG_CONNECTION_STATE;

void BBPGEventInputSend(BBPG_EVENT_INPUT_TYPE_T event);

#endif

