#define UART1_BAUDRATE     	UART_BAUDRATE_115K2       // Baudrate in bits/s: {9K6, 14K4, 19K2, 28K8, 38K4, 57K6, 115K2}
#define UART1_DATALENGTH   	UART_CHARFORMAT_8         // Datalength in bits: {5, 6, 7, 8}
#define UART1_PARITY       	UART_PARITY_NONE          // Parity: {UART_PARITY_NONE, UART_PARITY_EVEN, UART_PARITY_ODD}
#define UART1_STOPBITS     	UART_STOPBITS_1           // Stop bits: {UART_STOPBITS_1, UART_STOPBITS_2} 
#define UART1_FLOWCONTROL  	UART_FLOWCONTROL_DISABLED // Flow control: {UART_FLOWCONTROL_DISABLED, UART_FLOWCONTROL_ENABLED}

#define UART1_GPIO_PORT    	GPIO_PORT_0
#define UART1_TX_PIN       	GPIO_PIN_2
#define UART1_RX_PIN       	GPIO_PIN_3

#define UART_PRINTF_BUFFER_SIZE 128

#define MPU_I2C_GPIO_PORT  	GPIO_PORT_0
#define MPU_I2C_SCL_PIN    	GPIO_PIN_4
#define MPU_I2C_SDA_PIN    	GPIO_PIN_5

#define LED_PORT			GPIO_PORT_2
#define LED_RED_PIN		    GPIO_PIN_5
#define LED_GREEN_PIN		GPIO_PIN_6

#define OLED_POWER_GPIO_PORT GPIO_PORT_1
#define OLED_POWER_GPIO_PIN  GPIO_PIN_2

#define OLED_I2C_GPIO_PORT 	GPIO_PORT_0
#define OLED_I2C_SCL_PIN	GPIO_PIN_6
#define OLED_I2C_SDA_PIN	GPIO_PIN_7

#define OLED_RES_PORT       GPIO_PORT_1
#define OLED_RES_PIN        GPIO_PIN_1

#define TOUCH_IO_PORT       GPIO_PORT_2
#define TOUCH_IO_PIN        GPIO_PIN_2

#define SYSTEM_TIME_PERIOD  100 // unit ms





